name: dmp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 0.18.0
  carousel_slider: 2.2.1
  retrofit: any
  logger: any
  cupertino_icons: ^1.0.0
  flappy_search_bar: 1.7.2
  url_launcher: ^5.4.11
  flutter_money_formatter: ^0.8.3
  flutter_html: 0.11.1
  photo_view: 0.9.2
  cached_network_image: ^2.2.0+1
  flutter_range_slider: ^1.5.0
  moor_flutter: any
  translator: ^0.1.5
  animations: ^1.0.0+5
  flash: ^1.3.1
  analyzer: ^0.39.4
  provider: ^4.1.2
  shimmer: 1.1.1
  modal_progress_hud: ^0.1.3
  simple_animations: ^1.3.3
  flutter_webview_plugin: ^0.3.11
  geolocator: ^3.0.1
  permission_handler: ^3.2.2
  yandex_mapkit: ^0.3.9
  location: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  moor_generator: any
  build_runner: any


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/image/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
